### PR TITLE
Creating pathway created by the CLI

### PR DESCRIPTION
**Pull request by BenHall**

### CODE REVIEW

**Review by atheiman — COMMENTED** [review]
Thank you for the submission Ben, and all of your help with Katacoda so far! But from what I can tell this is relating my two katacoda scenarios into one training path? We dont need that as the two scenarios are not related, only `open-policy-agent-gatekeeper` is being used at devopsdays kc.

**Comment by BenHall** [comment]
@atheiman Updated

**Comment by atheiman** [comment]
After reading your email I think I understand this better and will try implementing this in some way before our workshop on thursday.

**Comment by atheiman** [comment]
pulled this in yesterday in a different commit. thanks for the help!

**Pull request closed without merging**
